"use client";

// This file is generated by scripts/build-stepper-registry.mjs.
// Edit components/ui/stepper/*, then run pnpm registry:build.

import * as React from "react";
import { Slot } from "@radix-ui/react-slot";

import { cn } from "@/lib/utils";

// components/ui/stepper/types.ts
type StepperOrientation = "horizontal" | "vertical";
type StepperStepPosition = "previous" | "current" | "next";
type StepperStepState =
  | "inactive"
  | "active"
  | "completed"
  | "disabled"
  | "error";

type StepRecord = {
  value: string;
  disabled: boolean;
};

type StepperStep = StepRecord;

type RegisteredStep = StepRecord & {
  element: HTMLLIElement | null;
  order: number;
};

type StepperNavigationGuard = () => boolean | Promise<boolean>;

type StepperApi = {
  value: string | undefined;
  orientation: StepperOrientation;
  steps: StepperStep[];
  currentIndex: number;
  totalSteps: number;
  setValue: (value: string) => void;
  getStepIndex: (value: string) => number;
  canGoPrevious: boolean;
  canGoNext: boolean;
  goPrevious: () => void;
  goNext: () => void;
};

type StepperContextValue = StepperApi & {
  registerStep: (step: Omit<RegisteredStep, "order">) => void;
  unregisterStep: (value: string) => void;
  getTriggerId: (value: string) => string;
  getContentId: (value: string) => string;
};

type StepperStepMeta = {
  currentValue: string | undefined;
  fallbackValue: string | undefined;
  selectedStep: StepRecord | undefined;
};

type StepperItemContextValue = {
  value: string;
  index: number;
  disabled: boolean;
  isActive: boolean;
  stepState: StepperStepState;
  stepPosition: StepperStepPosition;
  orientation: StepperOrientation;
  setValue: (value: string) => void;
  triggerId: string;
  contentId: string;
};

type StepperProps = React.ComponentPropsWithoutRef<"div"> & {
  value?: string;
  defaultValue?: string;
  onValueChange?: (value: string) => void;
  orientation?: StepperOrientation;
};

type StepperListProps = React.ComponentPropsWithoutRef<"ol">;

type StepperItemProps = Omit<
  React.ComponentPropsWithoutRef<"li">,
  "value"
> & {
  value: string;
  completed?: boolean;
  disabled?: boolean;
  error?: boolean;
};

type StepperTriggerProps = React.ComponentPropsWithoutRef<"button"> & {
  asChild?: boolean;
};

type StepperIndicatorProps = React.ComponentPropsWithoutRef<"span">;

type StepperLabelProps = React.ComponentPropsWithoutRef<"span">;

type StepperDescriptionProps = React.ComponentPropsWithoutRef<"span">;

type StepperSeparatorProps = React.ComponentPropsWithoutRef<"span">;

type StepperContentProps = React.ComponentPropsWithoutRef<"div"> & {
  value: string;
  forceMount?: boolean;
  asChild?: boolean;
};

type StepperButtonProps = React.ComponentPropsWithoutRef<"button"> & {
  asChild?: boolean;
};

type StepperPreviousProps = StepperButtonProps & {
  onBeforePrevious?: StepperNavigationGuard;
};

type StepperNextProps = StepperButtonProps & {
  onBeforeNext?: StepperNavigationGuard;
};

// components/ui/stepper/utils.ts
const STEPPER_PRIMITIVES = {
  content: "StepperContent",
  description: "StepperDescription",
  indicator: "StepperIndicator",
  item: "StepperItem",
  label: "StepperLabel",
  separator: "StepperSeparator",
  trigger: "StepperTrigger",
} as const;

type StepperPrimitiveName =
  (typeof STEPPER_PRIMITIVES)[keyof typeof STEPPER_PRIMITIVES];

type StepperPrimitiveComponent = React.ElementType & {
  displayName?: string;
  __stepperPrimitive?: StepperPrimitiveName;
  render?: unknown;
  type?: unknown;
};

function getSafeId(value: string) {
  return value.replace(/[^a-zA-Z0-9_-]/g, "-");
}

function getStepperPrimitiveName(type: unknown): StepperPrimitiveName | undefined {
  if (!type || (typeof type !== "function" && typeof type !== "object")) {
    return undefined;
  }

  const primitive = type as StepperPrimitiveComponent;

  if (primitive.__stepperPrimitive) {
    return primitive.__stepperPrimitive;
  }

  if (
    primitive.displayName &&
    Object.values(STEPPER_PRIMITIVES).includes(
      primitive.displayName as StepperPrimitiveName
    )
  ) {
    return primitive.displayName as StepperPrimitiveName;
  }

  return (
    getStepperPrimitiveName(primitive.type) ??
    getStepperPrimitiveName(primitive.render)
  );
}

function markStepperPrimitive<T extends StepperPrimitiveComponent>(
  component: T,
  name: StepperPrimitiveName
) {
  component.displayName = name;
  component.__stepperPrimitive = name;
}

function getNextEnabledStep(
  steps: StepRecord[],
  currentValue: string | undefined
) {
  const currentIndex = steps.findIndex((step) => step.value === currentValue);

  if (currentIndex === -1) {
    return undefined;
  }

  return steps.slice(currentIndex + 1).find((step) => !step.disabled);
}

function getPreviousEnabledStep(
  steps: StepRecord[],
  currentValue: string | undefined
) {
  const currentIndex = steps.findIndex((step) => step.value === currentValue);

  if (currentIndex === -1) {
    return undefined;
  }

  return steps
    .slice(0, currentIndex)
    .reverse()
    .find((step) => !step.disabled);
}

function getStepperStepMeta(
  steps: StepRecord[],
  selectedValue: string | undefined
): StepperStepMeta {
  const fallbackValue = steps.find((step) => !step.disabled)?.value;
  const selectedStep = steps.find((step) => step.value === selectedValue);
  const currentValue =
    selectedStep && !selectedStep.disabled ? selectedStep.value : fallbackValue;

  return {
    currentValue,
    fallbackValue,
    selectedStep,
  };
}

function toStepRecord(step: RegisteredStep): StepRecord {
  return {
    value: step.value,
    disabled: step.disabled,
  };
}

function sortRegisteredSteps(steps: RegisteredStep[]) {
  return [...steps].sort((firstStep, secondStep) => {
    const firstElement = firstStep.element;
    const secondElement = secondStep.element;

    if (
      firstElement &&
      secondElement &&
      firstElement !== secondElement &&
      typeof Node !== "undefined"
    ) {
      const position = firstElement.compareDocumentPosition(secondElement);

      if (position & Node.DOCUMENT_POSITION_FOLLOWING) {
        return -1;
      }

      if (position & Node.DOCUMENT_POSITION_PRECEDING) {
        return 1;
      }
    }

    return firstStep.order - secondStep.order;
  });
}

function areRegisteredStepsEqual(
  firstSteps: RegisteredStep[],
  secondSteps: RegisteredStep[]
) {
  if (firstSteps.length !== secondSteps.length) {
    return false;
  }

  return firstSteps.every((step, index) => {
    const nextStep = secondSteps[index];

    return (
      step.value === nextStep.value &&
      step.disabled === nextStep.disabled &&
      step.element === nextStep.element &&
      step.order === nextStep.order
    );
  });
}

function collectSteps(children: React.ReactNode) {
  const steps: StepRecord[] = [];

  React.Children.forEach(children, (child) => {
    if (!React.isValidElement(child)) {
      return;
    }

    const primitiveName = getStepperPrimitiveName(child.type);

    if (primitiveName === STEPPER_PRIMITIVES.item) {
      const props = child.props as Pick<StepperItemProps, "disabled" | "value">;

      steps.push({
        value: props.value,
        disabled: Boolean(props.disabled),
      });

      return;
    }

    if (primitiveName === STEPPER_PRIMITIVES.content) {
      return;
    }

    if (
      typeof child.props === "object" &&
      child.props !== null &&
      "children" in child.props
    ) {
      const childProps = child.props as { children?: React.ReactNode };

      collectSteps(childProps.children).forEach((step) => steps.push(step));
    }
  });

  return steps;
}

function hasStepperPrimitiveChild(
  children: React.ReactNode,
  name?: StepperPrimitiveName
): boolean {
  return React.Children.toArray(children).some((child) => {
    if (!React.isValidElement(child)) {
      return false;
    }

    const primitiveName = getStepperPrimitiveName(child.type);

    if (name ? primitiveName === name : primitiveName) {
      return true;
    }

    if (
      typeof child.props === "object" &&
      child.props !== null &&
      "children" in child.props
    ) {
      const childProps = child.props as { children?: React.ReactNode };

      return hasStepperPrimitiveChild(childProps.children, name);
    }

    return false;
  });
}

// components/ui/stepper/context.tsx
const StepperContext = React.createContext<StepperContextValue | null>(null);
const StepperItemContext =
  React.createContext<StepperItemContextValue | null>(null);
const StepperListContext = React.createContext(false);

function useStepperContext(component: string) {
  const context = React.useContext(StepperContext);

  if (!context) {
    throw new Error(`${component} must be used within Stepper`);
  }

  return context;
}

function useStepperItemContext(component: string) {
  const context = React.useContext(StepperItemContext);

  if (!context) {
    throw new Error(`${component} must be used within StepperItem`);
  }

  return context;
}

function useStepperListContext() {
  return React.useContext(StepperListContext);
}

function useStepper(): StepperApi {
  const context = useStepperContext("useStepper");

  return {
    value: context.value,
    orientation: context.orientation,
    steps: context.steps,
    currentIndex: context.currentIndex,
    totalSteps: context.totalSteps,
    setValue: context.setValue,
    getStepIndex: context.getStepIndex,
    canGoPrevious: context.canGoPrevious,
    canGoNext: context.canGoNext,
    goPrevious: context.goPrevious,
    goNext: context.goNext,
  };
}

// components/ui/stepper/root.tsx
type FallbackSyncState = {
  currentValue: string | undefined;
  selectedCollectedStepDisabled: boolean | undefined;
  selectedStepDisabled: boolean | undefined;
  selectedStepExists: boolean;
  selectedValue: string | undefined;
};

type FallbackSyncReason =
  | "missing"
  | "direct-disabled"
  | "registered-disabled";

function getControlledFallbackReason(
  state: FallbackSyncState
): FallbackSyncReason | undefined {
  if (state.selectedValue === undefined || state.currentValue === undefined) {
    return undefined;
  }

  if (state.selectedValue === state.currentValue) {
    return undefined;
  }

  if (!state.selectedStepExists) {
    return "missing";
  }

  if (state.selectedCollectedStepDisabled === true) {
    return "direct-disabled";
  }

  if (state.selectedStepDisabled === true) {
    return "registered-disabled";
  }

  return undefined;
}

function getDuplicateStepValues(steps: Array<{ value: string }>) {
  const seenValues = new Set<string>();
  const duplicateValues = new Set<string>();

  steps.forEach((step) => {
    if (seenValues.has(step.value)) {
      duplicateValues.add(step.value);
      return;
    }

    seenValues.add(step.value);
  });

  return Array.from(duplicateValues);
}

function Stepper({
  value,
  defaultValue,
  onValueChange,
  orientation = "horizontal",
  className,
  children,
  ...props
}: StepperProps) {
  const id = React.useId();
  const isControlled = value !== undefined;
  const [uncontrolledValue, setUncontrolledValue] = React.useState(defaultValue);
  const collectedSteps = React.useMemo(() => collectSteps(children), [children]);
  const duplicateStepValues = React.useMemo(
    () => getDuplicateStepValues(collectedSteps),
    [collectedSteps]
  );
  const duplicateStepValuesKey = duplicateStepValues.join("\0");
  const [registeredSteps, setRegisteredSteps] = React.useState<
    RegisteredStep[]
  >([]);
  const stepOrderRef = React.useRef(0);
  const steps = React.useMemo(
    () =>
      registeredSteps.length > 0
        ? registeredSteps.map((step) => {
            const collectedStep = collectedSteps.find(
              (currentStep) => currentStep.value === step.value
            );

            return {
              ...toStepRecord(step),
              disabled: collectedStep?.disabled ?? step.disabled,
            };
          })
        : collectedSteps,
    [collectedSteps, registeredSteps]
  );
  const selectedValue = isControlled ? value : uncontrolledValue;
  const { currentValue, selectedStep } = React.useMemo(
    () => getStepperStepMeta(steps, selectedValue),
    [selectedValue, steps]
  );
  const selectedCollectedStep = React.useMemo(
    () => collectedSteps.find((step) => step.value === selectedValue),
    [collectedSteps, selectedValue]
  );
  const fallbackSyncState = React.useMemo<FallbackSyncState>(
    () => ({
      currentValue,
      selectedCollectedStepDisabled: selectedCollectedStep?.disabled,
      selectedStepDisabled: selectedStep?.disabled,
      selectedStepExists: Boolean(selectedStep),
      selectedValue,
    }),
    [
      currentValue,
      selectedCollectedStep?.disabled,
      selectedStep,
      selectedValue,
    ]
  );
  const fallbackSyncStateRef =
    React.useRef<FallbackSyncState>(fallbackSyncState);
  const previousStep = React.useMemo(
    () => getPreviousEnabledStep(steps, currentValue),
    [currentValue, steps]
  );
  const nextStep = React.useMemo(
    () => getNextEnabledStep(steps, currentValue),
    [currentValue, steps]
  );
  const currentIndex = React.useMemo(
    () =>
      currentValue === undefined
        ? -1
        : steps.findIndex((step) => step.value === currentValue),
    [currentValue, steps]
  );

  const registerStep = React.useCallback(
    (step: Omit<RegisteredStep, "order">) => {
      setRegisteredSteps((currentSteps) => {
        if (currentSteps.length === 0) {
          stepOrderRef.current = 0;
        }

        const existingStep = currentSteps.find(
          (currentStep) => currentStep.value === step.value
        );
        const nextStepRecord: RegisteredStep = {
          ...step,
          order: existingStep?.order ?? stepOrderRef.current++,
        };
        const nextSteps = sortRegisteredSteps([
          ...currentSteps.filter(
            (currentStep) => currentStep.value !== step.value
          ),
          nextStepRecord,
        ]);

        return areRegisteredStepsEqual(currentSteps, nextSteps)
          ? currentSteps
          : nextSteps;
      });
    },
    []
  );

  const unregisterStep = React.useCallback((stepValue: string) => {
    setRegisteredSteps((currentSteps) =>
      currentSteps.filter((step) => step.value !== stepValue)
    );
  }, []);

  const setStepperValue = React.useCallback(
    (nextValue: string) => {
      const nextStepRecord = steps.find((step) => step.value === nextValue);

      if (!nextStepRecord || nextStepRecord.disabled) {
        return;
      }

      if (!isControlled) {
        setUncontrolledValue(nextValue);
      }

      onValueChange?.(nextValue);
    },
    [isControlled, onValueChange, steps]
  );

  React.useLayoutEffect(() => {
    fallbackSyncStateRef.current = fallbackSyncState;
  }, [fallbackSyncState]);

  React.useEffect(() => {
    if (
      process.env.NODE_ENV === "production" ||
      duplicateStepValues.length === 0
    ) {
      return;
    }

    duplicateStepValues.forEach((stepValue) => {
      console.warn(
        `StepperItem value "${stepValue}" is duplicated. Step values must be unique within a Stepper.`
      );
    });
  }, [duplicateStepValues, duplicateStepValuesKey]);

  React.useEffect(() => {
    const fallbackReason = getControlledFallbackReason(fallbackSyncState);

    if (!isControlled || !fallbackReason) {
      return;
    }

    const syncLatestFallback = () => {
      const latestState = fallbackSyncStateRef.current;

      if (
        getControlledFallbackReason(latestState) &&
        latestState.currentValue !== undefined
      ) {
        onValueChange?.(latestState.currentValue);
      }
    };

    if (fallbackReason !== "registered-disabled") {
      syncLatestFallback();
      return;
    }

    // Wrapped StepperItem components report disabled changes from layout effects.
    // Deferring avoids syncing from a stale registered disabled value.
    const timeout = window.setTimeout(syncLatestFallback, 0);

    return () => window.clearTimeout(timeout);
  }, [
    fallbackSyncState,
    isControlled,
    onValueChange,
  ]);

  const context = React.useMemo<StepperContextValue>(
    () => ({
      value: currentValue,
      orientation,
      steps,
      currentIndex,
      totalSteps: steps.length,
      registerStep,
      unregisterStep,
      setValue: setStepperValue,
      getStepIndex: (stepValue) =>
        steps.findIndex((step) => step.value === stepValue),
      getTriggerId: (stepValue) => `${id}-trigger-${getSafeId(stepValue)}`,
      getContentId: (stepValue) => `${id}-content-${getSafeId(stepValue)}`,
      canGoPrevious: Boolean(previousStep),
      canGoNext: Boolean(nextStep),
      goPrevious: () => {
        if (previousStep) {
          setStepperValue(previousStep.value);
        }
      },
      goNext: () => {
        if (nextStep) {
          setStepperValue(nextStep.value);
        }
      },
    }),
    [
      currentValue,
      currentIndex,
      id,
      nextStep,
      orientation,
      previousStep,
      registerStep,
      setStepperValue,
      steps,
      unregisterStep,
    ]
  );

  return (
    <StepperContext.Provider value={context}>
      <div
        data-slot="stepper"
        data-orientation={orientation}
        className={cn("flex flex-col gap-6", className)}
        {...props}
      >
        {children}
      </div>
    </StepperContext.Provider>
  );
}

// components/ui/stepper/list.tsx
function StepperList({
  className,
  "aria-label": ariaLabel = "Progress steps",
  children,
  ...props
}: StepperListProps) {
  const { orientation } = useStepperContext("StepperList");

  return (
    <StepperListContext.Provider value>
      <ol
        aria-label={props["aria-labelledby"] ? undefined : ariaLabel}
        data-slot="stepper-list"
        data-orientation={orientation}
        className={cn(
          "flex min-w-0",
          "data-[orientation=horizontal]:w-full data-[orientation=horizontal]:gap-3 data-[orientation=horizontal]:overflow-x-auto data-[orientation=horizontal]:pb-2",
          "data-[orientation=vertical]:flex-col data-[orientation=vertical]:gap-4",
          "[&>li:last-child_[data-slot=stepper-separator]]:hidden",
          className
        )}
        {...props}
      >
        {children}
      </ol>
    </StepperListContext.Provider>
  );
}

// components/ui/stepper/item.tsx
function StepperItem({
  value,
  completed = false,
  disabled = false,
  error = false,
  className,
  children,
  ...props
}: StepperItemProps) {
  const {
    value: currentValue,
    orientation,
    steps,
    registerStep,
    unregisterStep,
    setValue,
    getStepIndex,
    getTriggerId,
    getContentId,
  } = useStepperContext("StepperItem");
  const itemRef = React.useRef<HTMLLIElement>(null);
  const isInsideStepperList = useStepperListContext();
  const index = getStepIndex(value);
  const currentIndex =
    currentValue === undefined ? -1 : getStepIndex(currentValue);
  const isActive = currentValue === value;
  const stepPosition =
    currentIndex < 0 || index < 0
      ? "next"
      : index < currentIndex
        ? "previous"
        : index === currentIndex
          ? "current"
          : "next";
  const stepState: StepperStepState = disabled
    ? "disabled"
    : error
      ? "error"
      : isActive
        ? "active"
        : completed
          ? "completed"
          : "inactive";
  const hasCustomChildren = hasStepperPrimitiveChild(children);
  const hasCustomSeparator = hasStepperPrimitiveChild(
    children,
    STEPPER_PRIMITIVES.separator
  );
  const isLastStep = index >= 0 && index === steps.length - 1;
  const shouldRenderSeparator =
    isInsideStepperList &&
    !isLastStep &&
    (!hasCustomChildren || !hasCustomSeparator);

  React.useLayoutEffect(() => {
    if (!isInsideStepperList) {
      return;
    }

    registerStep({
      value,
      disabled,
      element: itemRef.current,
    });

    return () => unregisterStep(value);
  }, [disabled, isInsideStepperList, registerStep, unregisterStep, value]);

  React.useEffect(() => {
    if (process.env.NODE_ENV === "production" || isInsideStepperList) {
      return;
    }

    const timeout = window.setTimeout(() => {
      console.warn(
        `StepperItem with value "${value}" must be rendered inside StepperList to participate in step order.`
      );
    }, 0);

    return () => window.clearTimeout(timeout);
  }, [isInsideStepperList, value]);

  React.useEffect(() => {
    if (
      process.env.NODE_ENV === "production" ||
      !isInsideStepperList ||
      index >= 0
    ) {
      return;
    }

    const timeout = window.setTimeout(() => {
      console.warn(
        `StepperItem with value "${value}" could not be found in the Stepper order. Check that it is rendered inside StepperList and not hidden behind an unsupported wrapper.`
      );
    }, 0);

    return () => window.clearTimeout(timeout);
  }, [index, isInsideStepperList, value]);

  const itemContext = React.useMemo<StepperItemContextValue>(
    () => ({
      value,
      index,
      disabled,
      isActive,
      stepState,
      stepPosition,
      orientation,
      setValue,
      triggerId: getTriggerId(value),
      contentId: getContentId(value),
    }),
    [
      value,
      index,
      disabled,
      isActive,
      stepState,
      stepPosition,
      orientation,
      setValue,
      getTriggerId,
      getContentId,
    ]
  );

  return (
    <li
      ref={itemRef}
      data-slot="stepper-item"
      data-orientation={orientation}
      data-state={stepState}
      data-position={stepPosition}
      data-disabled={disabled ? "" : undefined}
      data-error={error ? "" : undefined}
      data-completed={completed ? "" : undefined}
      className={cn(
        "group/stepper-item relative flex min-w-0",
        "[--stepper-indicator-size:2.25rem] [--stepper-separator-offset:calc(var(--stepper-indicator-size)/2+0.125rem)]",
        "data-[orientation=horizontal]:min-w-24 data-[orientation=horizontal]:flex-1 data-[orientation=horizontal]:flex-col data-[orientation=horizontal]:items-center",
        "data-[orientation=vertical]:items-start data-[orientation=vertical]:gap-3",
        className
      )}
      {...props}
    >
      <StepperItemContext.Provider value={itemContext}>
        {hasCustomChildren ? (
          <>
            {children}
            {shouldRenderSeparator ? <StepperSeparator /> : null}
          </>
        ) : (
          <>
            <StepperTrigger>
              <StepperIndicator />
              <StepperLabel>{children}</StepperLabel>
            </StepperTrigger>
            {shouldRenderSeparator ? <StepperSeparator /> : null}
          </>
        )}
      </StepperItemContext.Provider>
    </li>
  );
}

function StepperTrigger({
  asChild = false,
  className,
  children,
  disabled,
  onClick,
  onKeyDown,
  tabIndex,
  ...props
}: StepperTriggerProps) {
  const {
    value,
    disabled: itemDisabled,
    isActive,
    stepState,
    orientation,
    setValue,
    triggerId,
    contentId,
  } = useStepperItemContext("StepperTrigger");
  const { steps, getTriggerId } = useStepperContext("StepperTrigger");
  const isDisabled = itemDisabled || disabled;
  const Comp = asChild ? Slot : "button";

  return (
    <Comp
      id={triggerId}
      type={asChild ? undefined : "button"}
      aria-current={isActive ? "step" : undefined}
      aria-controls={isActive ? contentId : undefined}
      aria-disabled={isDisabled ? true : undefined}
      disabled={asChild ? undefined : isDisabled}
      tabIndex={asChild && isDisabled ? -1 : tabIndex}
      data-slot="stepper-trigger"
      data-state={stepState}
      data-disabled={isDisabled ? "" : undefined}
      className={cn(
        "group inline-flex min-h-10 min-w-0 items-center gap-2 rounded-md text-left text-sm font-medium outline-none",
        "text-muted-foreground transition-[color,background-color,box-shadow,transform] active:scale-[0.96]",
        "focus-visible:ring-ring/50 focus-visible:ring-[3px]",
        "disabled:pointer-events-none disabled:opacity-50",
        "data-[disabled]:pointer-events-none data-[disabled]:opacity-50",
        "data-[state=active]:text-foreground",
        "data-[state=completed]:text-foreground",
        "data-[state=error]:text-destructive",
        orientation === "horizontal" && "w-full flex-col items-center text-center",
        orientation === "vertical" && "justify-start",
        className
      )}
      onClick={(event: React.MouseEvent<HTMLButtonElement>) => {
        onClick?.(event);

        if (isDisabled) {
          event.preventDefault();
          return;
        }

        if (!event.defaultPrevented) {
          setValue(value);
        }
      }}
      onKeyDown={(event: React.KeyboardEvent<HTMLButtonElement>) => {
        onKeyDown?.(event);

        if (event.defaultPrevented || isDisabled) {
          return;
        }

        const targetStepValue = getKeyboardNavigationStepValue({
          key: event.key,
          orientation,
          steps,
          value,
        });

        if (!targetStepValue || targetStepValue === value) {
          return;
        }

        const targetTrigger = document.getElementById(
          getTriggerId(targetStepValue)
        );

        if (targetTrigger instanceof HTMLElement) {
          event.preventDefault();
          targetTrigger.focus();
        }
      }}
      {...props}
    >
      {children}
    </Comp>
  );
}

function getKeyboardNavigationStepValue({
  key,
  orientation,
  steps,
  value,
}: {
  key: string;
  orientation: "horizontal" | "vertical";
  steps: StepperStep[];
  value: string;
}) {
  const enabledSteps = steps.filter((step) => !step.disabled);
  const currentIndex = enabledSteps.findIndex((step) => step.value === value);

  if (currentIndex < 0) {
    return undefined;
  }

  if (key === "Home") {
    return enabledSteps.at(0)?.value;
  }

  if (key === "End") {
    return enabledSteps.at(-1)?.value;
  }

  if (
    (orientation === "horizontal" && key === "ArrowRight") ||
    (orientation === "vertical" && key === "ArrowDown")
  ) {
    return enabledSteps[Math.min(currentIndex + 1, enabledSteps.length - 1)]
      ?.value;
  }

  if (
    (orientation === "horizontal" && key === "ArrowLeft") ||
    (orientation === "vertical" && key === "ArrowUp")
  ) {
    return enabledSteps[Math.max(currentIndex - 1, 0)]?.value;
  }

  return undefined;
}

function StepperIndicator({
  className,
  children,
  ...props
}: StepperIndicatorProps) {
  const { index, stepState } = useStepperItemContext("StepperIndicator");
  const stepNumber = index >= 0 ? index + 1 : undefined;
  const content =
    children !== undefined
      ? children
      : stepState === "error"
        ? "!"
        : stepState === "completed"
          ? "\u2713"
          : stepNumber
            ? stepNumber
            : null;

  return (
    <>
      {stepNumber ? (
        <span className="sr-only">Step {stepNumber}:</span>
      ) : null}
      <span
        aria-hidden="true"
        data-slot="stepper-indicator"
        className={cn(
          "flex size-(--stepper-indicator-size) shrink-0 items-center justify-center rounded-full border border-border bg-background text-xs font-semibold text-muted-foreground shadow-sm",
          "group-data-[state=active]:border-primary group-data-[state=active]:bg-primary group-data-[state=active]:text-primary-foreground",
          "group-data-[state=completed]:border-primary group-data-[state=completed]:bg-primary group-data-[state=completed]:text-primary-foreground",
          "group-data-[state=error]:border-destructive group-data-[state=error]:bg-destructive group-data-[state=error]:text-destructive-foreground",
          "group-data-[position=previous]:text-foreground",
          "[&>svg]:size-4 [&>svg]:shrink-0",
          className
        )}
        {...props}
      >
        {content}
      </span>
    </>
  );
}

function StepperLabel({ className, ...props }: StepperLabelProps) {
  const { orientation } = useStepperItemContext("StepperLabel");

  return (
    <span
      data-slot="stepper-label"
      className={cn(
        "min-w-0 leading-none",
        orientation === "horizontal" && "max-w-24 truncate",
        className
      )}
      {...props}
    />
  );
}

function StepperDescription({ className, ...props }: StepperDescriptionProps) {
  return (
    <span
      data-slot="stepper-description"
      className={cn(
        "text-xs leading-snug font-normal text-muted-foreground",
        className
      )}
      {...props}
    />
  );
}

function StepperSeparator({ className, ...props }: StepperSeparatorProps) {
  const { orientation } = useStepperItemContext("StepperSeparator");

  return (
    <span
      aria-hidden="true"
      data-slot="stepper-separator"
      className={cn(
        "overflow-hidden bg-muted-foreground/25 after:absolute after:inset-0 after:bg-primary after:content-['']",
        "after:transition-transform after:duration-[220ms] after:ease-out motion-reduce:after:transition-none",
        orientation === "horizontal" &&
          "absolute left-[calc(50%+var(--stepper-separator-offset))] right-[calc(-50%+var(--stepper-separator-offset))] top-[calc(var(--stepper-indicator-size)/2)] h-px after:origin-left after:scale-x-0 group-data-[state=completed]/stepper-item:after:scale-x-100",
        orientation === "vertical" &&
          "absolute left-[calc(var(--stepper-indicator-size)/2)] top-[calc(var(--stepper-indicator-size)+0.5rem)] h-[calc(100%-var(--stepper-indicator-size)+0.75rem)] w-px after:origin-top after:scale-y-0 group-data-[state=completed]/stepper-item:after:scale-y-100",
        className
      )}
      {...props}
    />
  );
}

markStepperPrimitive(StepperItem, STEPPER_PRIMITIVES.item);
markStepperPrimitive(StepperTrigger, STEPPER_PRIMITIVES.trigger);
markStepperPrimitive(StepperIndicator, STEPPER_PRIMITIVES.indicator);
markStepperPrimitive(StepperLabel, STEPPER_PRIMITIVES.label);
markStepperPrimitive(StepperDescription, STEPPER_PRIMITIVES.description);
markStepperPrimitive(StepperSeparator, STEPPER_PRIMITIVES.separator);

// components/ui/stepper/content.tsx
function StepperContent({
  value,
  forceMount = false,
  asChild = false,
  className,
  children,
  ...props
}: StepperContentProps) {
  const {
    value: currentValue,
    steps,
    getTriggerId,
    getContentId,
  } = useStepperContext("StepperContent");
  const isActive = currentValue === value;
  const hasMatchingStep = steps.some((step) => step.value === value);

  React.useEffect(() => {
    if (process.env.NODE_ENV === "production" || hasMatchingStep) {
      return;
    }

    const timeout = window.setTimeout(() => {
      console.warn(
        `StepperContent value "${value}" does not match any StepperItem. Content values should map to a step value.`
      );
    }, 0);

    return () => window.clearTimeout(timeout);
  }, [hasMatchingStep, value]);

  if (!forceMount && !isActive) {
    return null;
  }

  const Comp = asChild ? Slot : "div";

  return (
    <Comp
      id={getContentId(value)}
      role="region"
      aria-labelledby={getTriggerId(value)}
      data-slot="stepper-content"
      data-state={isActive ? "active" : "inactive"}
      hidden={forceMount ? !isActive : undefined}
      className={cn(
        "rounded-lg border border-border/70 bg-muted/25 p-4 text-sm text-foreground shadow-sm",
        className
      )}
      {...props}
    >
      {children}
    </Comp>
  );
}

markStepperPrimitive(StepperContent, STEPPER_PRIMITIVES.content);

// components/ui/stepper/navigation.tsx
async function resolveNavigationGuard(
  guard: (() => boolean | Promise<boolean>) | undefined
) {
  if (!guard) {
    return true;
  }

  return (await guard()) !== false;
}

function StepperPrevious({
  asChild = false,
  className,
  children = "Previous",
  disabled,
  onBeforePrevious,
  onClick,
  tabIndex,
  ...props
}: StepperPreviousProps) {
  const { canGoPrevious, goPrevious } = useStepperContext("StepperPrevious");
  const [isPending, setIsPending] = React.useState(false);
  const isDisabled = disabled || !canGoPrevious || isPending;
  const Comp = asChild ? Slot : "button";

  return (
    <Comp
      type={asChild ? undefined : "button"}
      disabled={asChild ? undefined : isDisabled}
      aria-disabled={isDisabled ? true : undefined}
      tabIndex={asChild && isDisabled ? -1 : tabIndex}
      data-slot="stepper-previous"
      data-disabled={isDisabled ? "" : undefined}
      className={cn(
        "inline-flex h-10 items-center justify-center gap-2 rounded-md border border-border bg-background px-4 text-sm font-medium text-foreground",
        "transition-[color,background-color,box-shadow,transform] hover:bg-muted hover:text-foreground active:scale-[0.96]",
        "focus-visible:ring-ring/50 focus-visible:ring-[3px] focus-visible:outline-none",
        "disabled:pointer-events-none disabled:opacity-50",
        "data-[disabled]:pointer-events-none data-[disabled]:opacity-50",
        "[&>svg]:size-4 [&>svg]:shrink-0",
        className
      )}
      onClick={async (event: React.MouseEvent<HTMLButtonElement>) => {
        onClick?.(event);

        if (isDisabled) {
          event.preventDefault();
          return;
        }

        if (event.defaultPrevented) {
          return;
        }

        setIsPending(true);

        try {
          const canNavigate = await resolveNavigationGuard(onBeforePrevious);

          if (canNavigate) {
            goPrevious();
          }
        } finally {
          setIsPending(false);
        }
      }}
      {...props}
    >
      {children}
    </Comp>
  );
}

function StepperNext({
  asChild = false,
  className,
  children = "Next",
  disabled,
  onBeforeNext,
  onClick,
  tabIndex,
  ...props
}: StepperNextProps) {
  const { canGoNext, goNext } = useStepperContext("StepperNext");
  const [isPending, setIsPending] = React.useState(false);
  const isDisabled = disabled || !canGoNext || isPending;
  const Comp = asChild ? Slot : "button";

  return (
    <Comp
      type={asChild ? undefined : "button"}
      disabled={asChild ? undefined : isDisabled}
      aria-disabled={isDisabled ? true : undefined}
      tabIndex={asChild && isDisabled ? -1 : tabIndex}
      data-slot="stepper-next"
      data-disabled={isDisabled ? "" : undefined}
      className={cn(
        "inline-flex h-10 items-center justify-center gap-2 rounded-md bg-primary px-4 text-sm font-medium text-primary-foreground",
        "transition-[background-color,box-shadow,transform] hover:bg-primary/90 active:scale-[0.96]",
        "focus-visible:ring-ring/50 focus-visible:ring-[3px] focus-visible:outline-none",
        "disabled:pointer-events-none disabled:opacity-50",
        "data-[disabled]:pointer-events-none data-[disabled]:opacity-50",
        "[&>svg]:size-4 [&>svg]:shrink-0",
        className
      )}
      onClick={async (event: React.MouseEvent<HTMLButtonElement>) => {
        onClick?.(event);

        if (isDisabled) {
          event.preventDefault();
          return;
        }

        if (event.defaultPrevented) {
          return;
        }

        setIsPending(true);

        try {
          const canNavigate = await resolveNavigationGuard(onBeforeNext);

          if (canNavigate) {
            goNext();
          }
        } finally {
          setIsPending(false);
        }
      }}
      {...props}
    >
      {children}
    </Comp>
  );
}

export {
  Stepper,
  StepperContent,
  StepperDescription,
  StepperIndicator,
  StepperItem,
  StepperLabel,
  StepperList,
  StepperNext,
  StepperPrevious,
  StepperSeparator,
  StepperTrigger,
  useStepper,
};

export type {
  StepperApi,
  StepperButtonProps,
  StepperContentProps,
  StepperDescriptionProps,
  StepperIndicatorProps,
  StepperItemProps,
  StepperLabelProps,
  StepperListProps,
  StepperNavigationGuard,
  StepperNextProps,
  StepperOrientation,
  StepperPreviousProps,
  StepperProps,
  StepperSeparatorProps,
  StepperStep,
  StepperStepPosition,
  StepperStepState,
  StepperTriggerProps,
};
